version: 2.1

orbs:
  qodana: jetbrains/qodana@2024.3

jobs:
  code-quality:
    machine:
      image: 'ubuntu-2004:current'
    environment: $QODANA_TOKEN
    steps:
      - checkout
      - qodana/scan:
          args: --fail-threshold 5

workflows:
  main:
    jobs:
      - code-quality:
          context: qodana


