version: 2.1

orbs:
  qodana: jetbrains/qodana@2024.3

jobs:
  code-quality:
    machine:
      image: 'ubuntu-2004:current'
    environment: $QODANA_TOKEN
    steps:
      - checkout
      - qodana/scan:
          args: --fail-threshold 30 --baseline baseline.json

workflows:
  main:
    jobs:
      - code-quality:
          context: qodana
          filters:
            branches:
              only:
                - feature  # Ersetze 'main' durch den gewünschten Branch-Namen


